=== youtufan/xml/xml实验汇总/第四次实验/anime.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT root (section)+>
<!ELEMENT section (origin,roletable,plot,frames)>
<!ATTLIST section section_id CDATA #REQUIRED>
<!ELEMENT origin (anime,original)>
<!ATTLIST origin country CDATA #REQUIRED>
<!ELEMENT anime (anime_content|producer)*>
<!ATTLIST anime anime_name CDATA #REQUIRED>
<!ELEMENT anime_content (#PCDATA)>
<!ELEMENT producer (#PCDATA)>
<!ATTLIST producer producer_name CDATA #REQUIRED>
<!ELEMENT original (author)>
<!ATTLIST original form (漫画|小说) "漫画">
<!ELEMENT author EMPTY>
<!ATTLIST author author_name CDATA #REQUIRED
                 author_gender (男|女) "男"
                 author_birth CDATA #REQUIRED
>
<!ELEMENT roletable (role)*>
<!ELEMENT role (#PCDATA)>
<!ATTLIST role role_name CDATA #REQUIRED
               role_gender (男|女) "男"
               role_age CDATA #IMPLIED
               role_cv CDATA #REQUIRED
>
<!ELEMENT plot (plot_content|linestable)*>
<!ATTLIST plot plot_classifier (战斗|鬼畜|恋爱|亲情|黑化|独白|变身|日常|抉择) "战斗">
<!ELEMENT plot_content (#PCDATA)>
<!ELEMENT linestable (lines)*>
<!ELEMENT lines (speaker,linestext)>
<!ATTLIST lines lines_id CDATA #REQUIRED>
<!ELEMENT speaker (#PCDATA)>
<!ELEMENT linestext (#PCDATA)>
<!ATTLIST linestext keyword CDATA #REQUIRED>
<!ELEMENT frames (#PCDATA)>
<!ATTLIST frames frames_classifier (黑白|自然|恢弘|暗黑|生活|甜蜜|萌系|血腥|暴力|人物) "生活">

=== youtufan/xml/xml实验汇总/第二次实验/王梦凡/wmf.3.xml
<?xml version="1.0" encoding="GB2312"?>
<?xml-stylesheet type="text/xsl" href="newone.xsl"?>
<!DOCTYPE root SYSTEM "anime.dtd">
<root>
 <section section_id="34">
  <!--34编写人：王梦凡-->
  <origin >
   <anime anime_name="我的英雄学院">
    <anime_content>二季10集</anime_content>
    <producer producer_name="Bones">BILIBILI</producer>
   </anime>
   <original form="漫画">
    <author author_name="堀越耕平" author_gender="男" author_birth="1986-11-20"/>
   </original>
  </origin>
  <roletable>
   <role role_name="绿谷出久" role_gender="男" role_age="16" role_cv="山下大辉">
本作的主人公，脸上有雀斑，看到有寻求帮助的人，就不顾一切冲上去的天生的英雄。有心事的时候就会手捂住嘴喃喃地嘟哝的毛病。出久是世上相当罕见的天生无个性之人(第五世代)，对英雄有着无比狂热的执念，习惯将世上活动的英雄们(包括他的同学们)的能力与事迹用笔记本进行总结，因此对英雄相关的知识非常丰富。
   </role>
  </roletable>
  <plot plot_classifier="战斗">  
   <plot_content>
  雄英高中的第一学期结束，在暑假期间进行林间集体特训，在第一天的特训结束之后，决定进行试胆大会，试胆大会期间敌人联合军对同学们发动了突袭。  
   </plot_content>
   <linestable>
    <lines lines_id="01">
    <speaker>铁哲</speaker>
    <linestext keyword="差距">同样是通过考试进入雄英学院，参加同样的课程，他们有我们没有的的东西，就是危机，那些家伙能把危机转换成机会</linestext>
    </lines>
    <lines lines_id="02">
    <speaker>绿谷出久</speaker>
    <linestext keyword="英雄">英雄是赌上自己的性命，将正确的事情变为现实</linestext>
    </lines>
    <lines lines_id="03">
    <speaker>欧尔迈特</speaker>
    <linestext keyword="英雄">英雄要经常突破险境</linestext>
    </lines>
   </linestable>
  </plot>
  <frames frames_classifier="自然">
   悬崖边的天然石洞
  </frames>
 </section>
 </root>

=== youtufan/xml/xml实验汇总/第四次实验/new5.xml
<?xml version="1.0" encoding="GB2312"?>
<?xml-stylesheet type="text/xsl" href="alldata.xsl"?>
<!DOCTYPE root SYSTEM "anime.dtd">
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    
      xsi:noNamespaceSchemaLocation="third.xsd">
<section section_id="36">
<!--36 编写人：邹仕艺-->
  <origin country="中国">
   <anime anime_name="熊出没">
    <anime_content>第一季第1集</anime_content>
    <producer producer_name="深圳华强数字动漫有限公司">爱奇艺乐视网</producer>
   </anime>
   <original form="漫画">
    <author author_name="丁亮" author_gender="男" author_birth="1973-05-18"/>
   </original>
  </origin>
  <roletable>
   <role role_name="熊大" role_gender="男" role_age="19" role_cv="张伟">
    狗熊
   </role> 
   <role role_name="熊二" role_gender="男" role_age="17" role_cv="张秉君">
    狗熊
   </role>
   <role role_name="光头强" role_gender="男" role_age="35" role_cv="谭笑">
    狗熊
   </role>
  </roletable>
  <plot plot_classifier="日常">
   <plot_content>  光头强带着电锯和枪来到风景优美的森林里伐木，森林的主人是两只狗熊，它们是熊大熊二。光头强要砍树，狗熊兄弟要阻止破坏森林的行为，光头强和两只臭狗熊之间围绕着保护森林这个主题展开。
   </plot_content>
   <linestable>
    <lines lines_id="1">
    <speaker>光头强</speaker>
    <linestext keyword="有趣">
     这头熊真有趣
    </linestext>
    </lines>
    <lines lines_id="2">
    <speaker>光头强</speaker>
    <linestext keyword="整片森林">
     不错不错，说不定这头熊还能帮着我砍树呢。哈哈哈哈哈，这整片森林都是我的了！
    </linestext>
    </lines>
   </linestable>
  </plot>
  <frames frames_classifier="萌系">
   熊二初次遇见光头强，被人类的美食所迷住，很可爱。
  </frames>
 </section>
 
 <section section_id="37">
  <!--37 编写人：邹仕艺-->
  <origin country="中国">
   <anime anime_name="熊出没">
    <anime_content>第一季第2集</anime_content>
    <producer producer_name="深圳华强数字动漫有限公司">爱奇艺乐视网</producer>
   </anime>
   <original form="漫画">
    <author author_name="丁亮" author_gender="男" author_birth="1973-05-18"/>
   </original>
  </origin>
  <roletable>
   <role role_name="熊大" role_gender="男" role_age="19" role_cv="张伟">
    狗熊
   </role> 
   <role role_name="熊二" role_gender="男" role_age="17" role_cv="张秉君">
    狗熊
   </role>
   <role role_name="光头强" role_gender="男" role_age="35" role_cv="谭笑">
    狗熊
   </role>
  </roletable>
  <plot plot_classifier="日常">
   <plot_content>  光头强和森林保护者熊兄弟之间上演熊熊的歌声。
   </plot_content>
   <linestable>
    <lines lines_id="1">
    <speaker>熊大</speaker>
    <linestext keyword="果然">
     果然又是光头强
    </linestext>
    </lines>    
   </linestable>
  </plot>
  <frames frames_classifier="萌系">
   熊二和熊大在认真的学习唱歌，却被光头强的电锯声所干扰。
  </frames>
 </section>

 <section section_id="38">
  <!--38 编写人：邹仕艺-->
  <origin country="中国">
   <anime anime_name="熊出没">
    <anime_content>第一季第3集</anime_content>
    <producer producer_name="深圳华强数字动漫有限公司">爱奇艺乐视网</producer>
   </anime>
   <original form="漫画">
    <author author_name="丁亮" author_gender="男" author_birth="1973-05-18"/>
   </original>
  </origin>
  <roletable>
   <role role_name="熊大" role_gender="男" role_age="19" role_cv="张伟">
    狗熊
   </role> 
   <role role_name="熊二" role_gender="男" role_age="17" role_cv="张秉君">
    狗熊
   </role>
   <role role_name="光头强" role_gender="男" role_age="35" role_cv="谭笑">
    狗熊
   </role>
  </roletable>
  <plot plot_classifier="日常">
   <plot_content>  
   伐木工光头强和两只熊的斗争，光头强要砍伐森林，熊大熊二要保护森林家园，在第五集中光头强买了一个机器人代替人工伐木。
   </plot_content>
   <linestable>
    <lines lines_id="1">
    <speaker>光头强</speaker>
    <linestext keyword="办法">
     都怪那两头小熊熊，每次都跑出来捣乱。可是，可是那又有什么办法呢？
    </linestext>
    </lines>    
   </linestable>
  </plot>
  <frames frames_classifier="萌系">
   光头强砍树又被熊大熊二所阻挠，气急败坏，抓耳挠腮很可爱。
  </frames>
 </section>
 
 <section section_id="39">
 <!--39 编写人：邹仕艺-->
  <origin country="中国">
   <anime anime_name="大耳朵图图">
    <anime_content>第一季第1集</anime_content>
    <producer producer_name=" 上海美术电影制片厂">腾讯视频</producer>
   </anime>
   <original form="漫画">
    <author author_name="速达" author_gender="男" author_birth="1983-12-18"/>
   </original>
  </origin>
  <roletable>
   <role role_name="胡图图" role_gender="男" role_age="3" role_cv="豆豆" />
    狗熊
  </roletable>
  <plot plot_classifier="日常">
   <plot_content>    图图和小美讨论孩子是从哪里来的，壮壮得意地告诉他们小孩子是商店里买来的。图图回家告诉了妈妈后，妈妈无奈的说孩子是医院的“魔术师”从妈妈肚子里变出来的。丁玎阿姨要生小宝宝了，图图吵着跟妈妈去医院看孩子，却闹出让医生哭笑不得的笑话。
   </plot_content>
   <linestable>
    <lines lines_id="1">
    <speaker>胡图图</speaker>
    <linestext keyword="垃圾桶">
     不是的，胡图图是从垃圾桶捡来的。
    </linestext>
    </lines>    
    <lines lines_id="2">
    <speaker>胡图图</speaker>
    <linestext keyword="绝对">
     绝对？壮壮哥哥绝对是什么。
    </linestext>
    </lines>    
   </linestable>
  </plot>
  <frames frames_classifier="萌系">
   小美，胡图图和壮壮讨论自己是怎么来的。非常天真可爱。
  </frames>
 </section>
 
<section section_id="40">
 <!--40 编写人：邹仕艺-->
  <origin country="中国">
   <anime anime_name="大耳朵图图">
    <anime_content>第一季第2集</anime_content>
    <producer producer_name=" 上海美术电影制片厂">腾讯视频</producer>
   </anime>
   <original form="漫画">
    <author author_name="速达" author_gender="男" author_birth="1983-12-18"/>
   </original>
  </origin>
  <roletable>
   <role role_name="胡图图" role_gender="男" role_age="3" role_cv="豆豆" />
    狗熊
  </roletable>
  <plot plot_classifier="日常">
   <plot_content>    图图过生日，家人问他想要什么礼物，图图的答案出人意料__想要一个哥哥。爸爸妈妈心知儿子的孤单，想了各种解决问题的办法，最后爸爸从乡下爷爷那儿抱来了一只可爱的小花猫，图图给不爱吃鱼爱吃蔬菜的小猫取名小怪，并度过了一个快乐的生日。
   </plot_content>
   <linestable>
    <lines lines_id="1">
    <speaker>胡图图</speaker>
    <linestext keyword="生日">
     生日？是不是要吃好吃的东西呀？
    </linestext> 
    </lines>
   </linestable>
  </plot>
  <frames frames_classifier="萌系">
   当胡图图爸爸问胡图图过生日的时候想要什么，胡图图得知生日可以吃很多好吃的，非常兴奋可爱。
  </frames>
 </section>
 
</root>
