=== youtufan/xml/xml实验汇总/第三次实验/third.xsd
<?xml version="1.0" encoding="GB2312"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="section" minOccurs="1" maxOccurs="100"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="ageType">
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="100"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="section">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="origin"/>
				<xs:element ref="roletable"/>
				<xs:element ref="plot"/>
				<xs:element ref="frames"/>
			</xs:sequence>
			<xs:attribute name="section_id" type="ageType" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="origin">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="anime"/>
				<xs:element ref="original"/>
			</xs:sequence>
			<xs:attribute name="country" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="anime">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element name="anime_content" type="xs:string"/>
				<xs:element ref="producer"/>
			</xs:sequence>
			<xs:attribute name="anime_name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="producer">
		<xs:complexType mixed="true">
			<xs:attribute name="producer_name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="formType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="小说"/>
			<xs:enumeration value="漫画"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="sexType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="男"/>
			<xs:enumeration value="女"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="original">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="author"/>
			</xs:sequence>
			<xs:attribute name="form" type="formType" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="author">
		<xs:complexType mixed="true">
			<xs:attribute name="author_name" type="xs:string" use="required"/>
			<xs:attribute name="author_gender" type="sexType" use="required"/>
			<xs:attribute name="author_birth" type="xs:date" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="roletable">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="role" minOccurs="1" maxOccurs="100"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="role">
		<xs:complexType mixed="true">
			<xs:attribute name="role_name" type="xs:string" use="required"/>
			<xs:attribute name="role_gender" type="sexType" use="required"/>
			<xs:attribute name="role_age" type="ageType" use="required"/>
			<xs:attribute name="role_cv" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="plotType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="战斗"/>
			<xs:enumeration value="鬼畜"/>
			<xs:enumeration value="恋爱"/>
			<xs:enumeration value="亲情"/>
			<xs:enumeration value="黑化"/>
			<xs:enumeration value="独白"/>
			<xs:enumeration value="变身"/>
			<xs:enumeration value="日常"/>
			<xs:enumeration value="抉择"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="plot">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element name="plot_content" type="xs:string"/>
				<xs:choice minOccurs="0">
					<xs:element ref="linestable"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="plot_classifier" type="plotType" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="linestable">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="lines" minOccurs="1" maxOccurs="100"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="lines">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="speaker"/>
				<xs:element ref="linestext"/>
			</xs:sequence>
			<xs:attribute name="lines_id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="speaker" type="xs:string"/>
	<xs:element name="linestext">
		<xs:complexType mixed="true">
			<xs:attribute name="keyword" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="framesType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="黑白"/>
			<xs:enumeration value="自然"/>
			<xs:enumeration value="恢弘"/>
			<xs:enumeration value="暗黑"/>
			<xs:enumeration value="生活"/>
			<xs:enumeration value="甜蜜"/>
			<xs:enumeration value="暴力"/>
			<xs:enumeration value="血腥"/>
			<xs:enumeration value="人物"/>
			<xs:enumeration value="萌系"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="frames">
		<xs:complexType mixed="true">
			<xs:attribute name="frames_classifier" type="framesType" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== youtufan/xml/xml实验汇总/第二次实验/张孙兰馨/VEpost.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="VEpost.xsl"?>
<!DOCTYPE root SYSTEM "anime.dtd">
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    
      xsi:noNamespaceSchemaLocation="third.xsd">
<section section_id="31">
  <!--31编写人：张孙兰馨-->
  <origin>
   <anime anime_name="紫罗兰永恒花园">
    <anime_content>第一季特别篇</anime_content>
    <producer producer_name="京都动画">BILIBILI</producer>
   </anime>
   <original form="小说">
    <author author_name="晓佳奈" author_gender="女" author_birth="1986-04-20"/>
   </original>
  </origin>
  <roletable>
   <role role_name="薇尔莉特_伊芙加登" role_gender="女" role_age="14" role_cv="石川由依">
    小时候作为军人参加了大战，因为受到军事教育影响，不能很好地理解别人的感情。在C_H邮政公司开始工作的新人自动手记人偶。
   </role>
   <role role_name="奥尔多" role_gender="男" role_age="45" role_cv="安原义人">
    厄玛的好友，与厄玛一起合作创作歌剧。
   </role>
   <role role_name="厄玛" role_gender="女" role_age="30" role_cv="日笠阳子">
   有名的歌剧演员，恋人在战争中失踪，战争结束后委托奥尔多一起创作有关开辟和平年代的现代歌剧。
   </role>
  </roletable>
  <plot plot_classifier="抉择">
  <plot_content>
   奥尔多带着薇尔莉特去看厄玛的排练，告诉她厄玛真正的目的，委托薇尔莉特再尝试接受委托。
   </plot_content>
   <linestable>
    <lines lines_id="01">
     <speaker>厄玛</speaker>
     <linestext keyword="新的时代">战争结束，本该迎来和平年代。可大家真的幸福了吗？要开辟新的时代！靠我们每一个人！</linestext>
    </lines>
    <lines lines_id="02">
     <speaker>奥尔多</speaker>
     <linestext keyword="冻结的心">那场战争给太多人留下了伤痕，如今那些人的心里依然冻结着，既无法感受到新时代来临，也无法举步向前。</linestext>
    </lines>
   </linestable>
  </plot>
  <frames frames_classifier="生活">
   奥尔多和薇尔莉特在剧场的幕布后看厄玛排练，唱出歌词。
  </frames>
 </section>
 </root>

=== youtufan/xml/xml实验汇总/第二次实验/邹仕艺/Untitled4.xml
<?xml version="1.0" encoding="GB2312"?>
<?xml-stylesheet type="text/xsl" href="Untitled10.xsl"?>
<!DOCTYPE root SYSTEM "anime.dtd">
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="third.xsd">
	<section section_id="01">
		<!--01编写人：邹仕艺-->
		<origin>
			<anime anime_name="东京食尸鬼">
              <anime_content>第一季第12集</anime_content>
                <producer producer_name="Studio Pierrot">BILIBILI</producer>
			</anime>
			<original form="漫画">
				<author author_name="石田翠" author_gender="男" author_birth="1973-06-28"/>
			</original>
		</origin>
		
		<roletable>
			<role role_name="金木研" role_gender="男" role_age="19" role_cv="花江夏树">
             人类→半食种（改造混血）
            </role>
		</roletable>
		 
		<plot plot_classifier="黑化">   
		    <plot_content>金木研被青铜树组织掳走，面对神代利世对峙要挟和壁虎的残忍折磨，最终黑化成青铜树组织一员，实则为了保护英同学和古董咖啡店的朋友不受伤害。		 
		    </plot_content>
            <linestable>
				<lines lines_id="1">
					<speaker>金木研</speaker>
					                        
					<linestext keyword="超越/选择错误">错的不是我，是这个世界</linestext>
				</lines>
				
				<lines lines_id="2">
					<speaker>神代利世</speaker>
					
					<linestext keyword="弱肉强食">
                       生存就意味着弱肉强食
                    </linestext>
				</lines>
				
			</linestable>
		</plot>
		
		<frames frames_classifier="暗黑">		
        用彼岸花从洁白变成血红色来暗示金木研从人类思想转变为血腥的食种. 
        </frames>
	</section>
</root>
